/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all companies */
        get: operations["CompaniesController_findAll"];
        put?: never;
        /** Create a new company */
        post: operations["CompaniesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a company by ID */
        get: operations["CompaniesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects or filter by company */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a new project */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID */
        get: operations["ProjectsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["ProjectsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCompanyDto: {
            /**
             * @description Company name
             * @example Green Homes Developers
             */
            name: string;
            /**
             * @description Unique company slug
             * @example green-homes-developers
             */
            slug: string;
            /**
             * @description Company email address
             * @example info@greenhomes.com
             */
            email: string;
            /**
             * @description Company phone number
             * @example +1 555-123-4567
             */
            phone: string;
            /**
             * @description Company website URL
             * @example https://greenhomes.com
             */
            website?: string;
            /**
             * @description Company address
             * @example 123 Palm Street, New City
             */
            address: string;
            /**
             * @description City
             * @example New City
             */
            city: string;
            /**
             * @description State/Province
             * @example California
             */
            state: string;
            /**
             * @description Country
             * @example USA
             */
            country: string;
            /**
             * @description Latitude coordinate
             * @example 34.0522
             */
            latitude?: number;
            /**
             * @description Longitude coordinate
             * @example -118.2437
             */
            longitude?: number;
            /**
             * @description Company description
             * @example Leading real estate company specializing in eco-friendly housing plots.
             */
            description?: string;
            /**
             * @description Company logo URL
             * @example https://cdn.example.com/logos/greenhomes.png
             */
            logoUrl?: string;
            /**
             * @description Company cover image URL
             * @example https://cdn.example.com/banners/greenhomes.jpg
             */
            coverImageUrl?: string;
            /**
             * @description Year the company was established
             * @example 2020
             */
            yearEstablished?: number;
            /**
             * @description Company type
             * @example DEVELOPER
             * @enum {string}
             */
            type: "DEVELOPER" | "BROKER" | "AGENT" | "CONSULTANT";
            /**
             * @description Company status
             * @default ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
            /**
             * @description User ID who created the company
             * @example user-123
             */
            createdBy: string;
        };
        Company: {
            /**
             * @description Unique company identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Company name
             * @example Green Homes Developers
             */
            name: string;
            /**
             * @description Unique company slug
             * @example green-homes-developers
             */
            slug: string;
            /**
             * @description Company email address
             * @example info@greenhomes.com
             */
            email: string;
            /**
             * @description Company phone number
             * @example +1 555-123-4567
             */
            phone: string;
            /**
             * @description Company website URL
             * @example https://greenhomes.com
             */
            website?: string;
            /**
             * @description Company address
             * @example 123 Palm Street, New City
             */
            address: string;
            /**
             * @description City
             * @example New City
             */
            city: string;
            /**
             * @description State/Province
             * @example California
             */
            state: string;
            /**
             * @description Country
             * @example USA
             */
            country: string;
            /**
             * @description Latitude coordinate
             * @example 34.0522
             */
            latitude?: number;
            /**
             * @description Longitude coordinate
             * @example -118.2437
             */
            longitude?: number;
            /**
             * @description Company description
             * @example Leading real estate company specializing in eco-friendly housing plots.
             */
            description?: string;
            /**
             * @description Company logo URL
             * @example https://cdn.example.com/logos/greenhomes.png
             */
            logoUrl?: string;
            /**
             * @description Company cover image URL
             * @example https://cdn.example.com/banners/greenhomes.jpg
             */
            coverImageUrl?: string;
            /**
             * @description Year the company was established
             * @example 2020
             */
            yearEstablished?: number;
            /**
             * @description Company type
             * @example DEVELOPER
             * @enum {string}
             */
            type: "DEVELOPER" | "BROKER" | "AGENT" | "CONSULTANT";
            /**
             * @description Company status
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "SUSPENDED";
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-10-25T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2025-10-25T10:00:00Z
             */
            updatedAt: string;
            /**
             * @description User ID who created the company
             * @example user-123
             */
            createdBy: string;
        };
        CreateProjectDto: {
            /**
             * @description Project name
             * @example Green Valley Residential
             */
            name: string;
            /**
             * @description Minimum land size in square meters
             * @example 500
             */
            minLandSize: number;
            /**
             * @description Minimum total price
             * @example 150000
             */
            minTotalPrice: number;
            /**
             * @description Minimum price per square meter
             * @example 300
             */
            minPricePerSqMeter: number;
            /**
             * @description Project description
             * @example Beautiful residential plots in a prime location with modern amenities.
             */
            description: string;
            /**
             * @description Location latitude
             * @example 34.0522
             */
            latitude: number;
            /**
             * @description Location longitude
             * @example -118.2437
             */
            longitude: number;
            /**
             * @description Location name or address
             * @example 123 Palm Street, New City, CA
             */
            locationName: string;
            /**
             * @description Array of project photo URLs
             * @example [
             *       "https://cdn.example.com/project1.jpg",
             *       "https://cdn.example.com/project2.jpg"
             *     ]
             */
            photos?: string[];
            /**
             * @description Cover photo URL
             * @example https://cdn.example.com/cover.jpg
             */
            coverPhotoUrl?: string;
            /**
             * @description Project video URL
             * @example https://cdn.example.com/video.mp4
             */
            videoUrl?: string;
            /**
             * @description Property type
             * @example land
             * @enum {string}
             */
            propertyType: "land" | "land_with_house";
            /**
             * @description Available communications and utilities
             * @example [
             *       {
             *         "type": "gas",
             *         "available": true,
             *         "description": "Natural gas connection"
             *       },
             *       {
             *         "type": "water",
             *         "available": true,
             *         "description": "Water supply connection"
             *       },
             *       {
             *         "type": "sewerage",
             *         "available": false,
             *         "description": "Sewerage system"
             *       },
             *       {
             *         "type": "road",
             *         "available": true,
             *         "description": "Road access"
             *       },
             *       {
             *         "type": "electricity",
             *         "available": true,
             *         "description": "Electrical connection"
             *       },
             *       {
             *         "type": "internet",
             *         "available": false,
             *         "description": "Internet connection"
             *       }
             *     ]
             */
            communications?: string[];
            /**
             * @description Project status
             * @default ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description Company ID this project belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            companyId: string;
        };
        Project: {
            /**
             * @description Unique project identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Project name
             * @example Green Valley Residential
             */
            name: string;
            /**
             * @description Developer company name
             * @example Green Homes Developers
             */
            developerCompanyName: string;
            /**
             * @description Developer company contact information
             * @example info@greenhomes.com, +1 555-123-4567
             */
            developerContactInfo: string;
            /**
             * @description Developer company photo URL
             * @example https://cdn.example.com/logos/greenhomes.png
             */
            developerPhotoUrl?: string;
            /**
             * @description Minimum land size in square meters
             * @example 500
             */
            minLandSize: number;
            /**
             * @description Minimum total price
             * @example 150000
             */
            minTotalPrice: number;
            /**
             * @description Minimum price per square meter
             * @example 300
             */
            minPricePerSqMeter: number;
            /**
             * @description Project description
             * @example Beautiful residential plots in a prime location with modern amenities.
             */
            description: string;
            /**
             * @description Location latitude
             * @example 34.0522
             */
            latitude: number;
            /**
             * @description Location longitude
             * @example -118.2437
             */
            longitude: number;
            /**
             * @description Location name or address
             * @example 123 Palm Street, New City, CA
             */
            locationName: string;
            /**
             * @description Array of project photo URLs
             * @example [
             *       "https://cdn.example.com/project1.jpg",
             *       "https://cdn.example.com/project2.jpg"
             *     ]
             */
            photos?: string[];
            /**
             * @description Cover photo URL
             * @example https://cdn.example.com/cover.jpg
             */
            coverPhotoUrl?: string;
            /**
             * @description Project video URL
             * @example https://cdn.example.com/video.mp4
             */
            videoUrl?: string;
            /**
             * @description Property type
             * @example land
             * @enum {string}
             */
            propertyType: "land" | "land_with_house";
            /**
             * @description Available communications and utilities
             * @example [
             *       {
             *         "type": "gas",
             *         "available": true,
             *         "description": "Natural gas connection"
             *       },
             *       {
             *         "type": "water",
             *         "available": true,
             *         "description": "Water supply connection"
             *       },
             *       {
             *         "type": "electricity",
             *         "available": true,
             *         "description": "Electrical connection"
             *       }
             *     ]
             */
            communications: string[];
            /**
             * @description Project status
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-10-25T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2025-10-25T10:00:00Z
             */
            updatedAt: string;
            /**
             * @description Company ID this project belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            companyId: string;
        };
        UpdateProjectDto: {
            /**
             * @description Project name
             * @example Green Valley Residential
             */
            name?: string;
            /**
             * @description Minimum land size in square meters
             * @example 500
             */
            minLandSize?: number;
            /**
             * @description Minimum total price
             * @example 150000
             */
            minTotalPrice?: number;
            /**
             * @description Minimum price per square meter
             * @example 300
             */
            minPricePerSqMeter?: number;
            /**
             * @description Project description
             * @example Beautiful residential plots in a prime location with modern amenities.
             */
            description?: string;
            /**
             * @description Location latitude
             * @example 34.0522
             */
            latitude?: number;
            /**
             * @description Location longitude
             * @example -118.2437
             */
            longitude?: number;
            /**
             * @description Location name or address
             * @example 123 Palm Street, New City, CA
             */
            locationName?: string;
            /**
             * @description Array of project photo URLs
             * @example [
             *       "https://cdn.example.com/project1.jpg",
             *       "https://cdn.example.com/project2.jpg"
             *     ]
             */
            photos?: string[];
            /**
             * @description Cover photo URL
             * @example https://cdn.example.com/cover.jpg
             */
            coverPhotoUrl?: string;
            /**
             * @description Project video URL
             * @example https://cdn.example.com/video.mp4
             */
            videoUrl?: string;
            /**
             * @description Property type
             * @example land
             * @enum {string}
             */
            propertyType?: "land" | "land_with_house";
            /**
             * @description Available communications and utilities
             * @example [
             *       {
             *         "type": "gas",
             *         "available": true,
             *         "description": "Natural gas connection"
             *       },
             *       {
             *         "type": "water",
             *         "available": true,
             *         "description": "Water supply connection"
             *       },
             *       {
             *         "type": "sewerage",
             *         "available": false,
             *         "description": "Sewerage system"
             *       },
             *       {
             *         "type": "road",
             *         "available": true,
             *         "description": "Road access"
             *       },
             *       {
             *         "type": "electricity",
             *         "available": true,
             *         "description": "Electrical connection"
             *       },
             *       {
             *         "type": "internet",
             *         "available": false,
             *         "description": "Internet connection"
             *       }
             *     ]
             */
            communications?: string[];
            /**
             * @description Project status
             * @default ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description Company ID this project belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            companyId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CompaniesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
        };
    };
    CompaniesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyDto"];
            };
        };
        responses: {
            /** @description Company successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Bad request - validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict - company with email or slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompaniesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Company UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Company not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter projects by company ID */
                companyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            /** @description Project successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request - validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Company not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            /** @description Project successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request - validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
